client/package.json
client/yarn.lock

fix: Install styled-components

---

client/src/components/WishButton.tsx

'filled' property를 True로 설정하면 하트가 채워짐
- resolved #9

feat:  찜 버튼 컴포넌트 구현

---

client/src/components/ShoppingCart.js

쇼핑카드 증가, 감소에 대한 이벤트 처리
- resolved #13

feat: 쇼핑카트 컴포넌트 코드 작성

---

client/package.json
client/src/components/footer.tsx

footer 아이콘 추가
material-ui설치
- resolved #17 
https://www.daleseo.com/material-ui-icons/

style: footer 아이콘 추가

---

server/prisma/.env.sample
server/src/graphql/index.ts

하나로 합쳤습니다
덤으로 prisma env sample도 만들었습니다
- resolved #27

import문 병합

---

server/prisma/schema.prisma

feat: Create prisma user model

---

server/prisma/.env.sample
server/prisma/schema.prisma
server/src/graphql/resolvers/category.ts

ERD에 있는 모든 테이블에 대한 schema 작성
- resolved #30

Prisma Schema 작성

---

server/package.json
server/src/graphql/resolvers/product.ts
server/src/graphql/types/category.graphql
server/src/graphql/types/product.graphql
server/yarn.lock

기본 CRUD만 구현
회원 기능 구현 후 추가적인 기능 구현 예정
- resolved #42

product API

---

server/package.json
server/prisma/schema.prisma
server/src/passport.ts
server/src/server.ts
server/src/userController.ts
server/yarn.lock

구글 로그인 기능 추가
/api/google 로 요청을 보내면 구글 로그인 후 유저와 유저 프로필 생성
JWT는 추후 적용 예정
- resolved #57

Han song2/issue57

---

client/src/components/PullToRefresh.tsx
client/src/pages/MainPage.tsx
client/src/utils/addPointerEventHandlers.ts
client/src/utils/index.ts

- 당겨서 새로고침 구현
- 덤으로 랜덤으로 메뉴 골라주기도 구현
- 메뉴나 시간 등은 하드코딩됨. 리팩터가 필요합니다.
- resolved #48

Pull to refresh 구현

---

client/src/components/ArrowFront.tsx
client/src/components/Header.tsx
client/src/components/main/Category.js
client/src/components/main/Product.js
client/src/components/main/category/ProductCategory.js
client/src/components/main/common/More.js
client/src/components/main/discount/ProductFlashDiscount.js
client/src/components/main/new/ProductNew.js
client/src/components/main/sellGood/ProductSellGood.js
client/src/pages/MainPage.tsx

메인페이지에 있는 카테고리 컴포넌트를 작성했습니다.
기타 스타일을 수정했습니다.
카테고리는 추가 리펙토링이 필요합니다(데이터 불러오는 부분)
- resolved #61

메인페이지 카테고리 컴포넌트 작성

---

client/src/components/category/CategoryContent.js
client/src/components/main/discount/ProductDiscount.js
client/src/components/main/discount/ProductFlashDiscount.js
client/src/components/main/new/ProductNew.js
client/src/components/main/nowEssential/ProductEssential.js
client/src/components/main/readyFor/ProductReadyFor.js
client/src/components/main/sellGood/ProductSellGood.js
client/src/components/main/whatEat/ProductWhatEat.js
client/src/utils/random.js

메인페이지 상품컴포넌트의 데이터를
데이터베이스와 연동해서 가져왔습니당
랜덤하게 가져와집니다.
- resolved #92

상품컴포넌트 데이터베이스 연동

---

client/src/components/PullToRefresh.tsx
client/src/components/main/common/ProductPhoto.js
client/src/components/main/discount/ProductDiscount.js
client/src/components/main/discount/ProductFlashDiscount.js
client/src/hooks/useScrollDiff.ts
client/src/pages/MainPage.tsx
client/src/utils/addEventListenerEffect.ts

- custom hook(useScrollDiff)를 이용해 땡겨요 리팩터. 훅 이름 추천해주세요.
- "땡겨요" 랜더에 대한 제어권을 MainPage로 옮김.
- "땡겨요" 메뉴가 돌아갈 때 다른데 클릭하면 처음부터 다시 돌아가던 버그 수정
- eslint warning을 없앴습니다

땡겨요 리팩터, 버그 수정

---

client/src/components/category/CategoryContent.js

map으로 바꿔서 생긴 오류 수정
- resolved #101

chore: 오류 수정

---

server/src/graphql/resolvers/category.ts
server/src/graphql/resolvers/product.ts
server/src/graphql/types/category.graphql
server/src/graphql/types/product.graphql

category API 누락된 부분

---

client/src/index.tsx
server/src/passportConfig.ts

- JWT 토큰에 유저 이름 추가
- 클라이언트에서 테스트 토큰 대신 진짜 토큰 전송

JWT 유저 정보 수정

---

client/src/App.tsx
client/src/components/CategoryDetail/CategoryHeader.js
client/src/components/CategoryDetail/CategoryProduct.js
client/src/pages/CategoryDetailPage.tsx

헤더 텍스트 설정
더보기 기능
뒤로가기버튼
- resolved #128

feat: 더보기 url 연결 및 헤더 설정

---

client/src/components/CategoryDetail/CategoryHeader.js
client/src/components/main/ProductEssential.tsx
client/src/components/main/ProductFlashDiscount/ProductFlashDiscount.js
client/src/components/main/ProductWhatEat.tsx
client/src/components/main/common/ProductContent.js
client/src/components/main/common/ProductInfo.js
client/src/components/main/hooks/useLazyRandomEssential.tsx
client/src/components/main/hooks/useLazyRandomProducts.tsx

장바구니를 수정했습니다.
refresh버튼 활성화 하는중입니다.. 내일 마저 하려합니다
- resolved #128

장바구니 수정, refresh부분 하는중

---

client/src/App.tsx
client/src/components/Footer.tsx
client/src/components/main/category/CategoryNavbar.tsx
client/src/components/main/category/CategoryProductItem.tsx
client/src/components/main/category/CategoryProductList.tsx
client/src/components/main/common/ProductInfo.js

더보기 링크를 연결하고,
footer 수정
- resolved #143

더보기 링크를 연결

---

client/src/App.tsx

카트 불러오기 버그 수정
- resolved #이슈넘버

fix: 카트 불러오기

---

client/src/components/main/common/ProductContent.js

chore : 50

---

client/src/components/CategoryDetail/ProductHowAbout.js
client/src/components/Footer.tsx
client/src/components/Header.tsx
client/src/components/PullToRefresh.tsx
client/src/components/main/ProductNew.tsx
client/src/components/main/ProductReadyFor.tsx
client/src/components/main/ProductSellGood.tsx
client/src/components/main/category/CategoryNavbar.tsx
client/src/components/main/category/CategoryProductList.tsx
client/src/index.css

feat: 최대 너비 제한
